### ISSUE TITLE
getting - Product is not enabled

### ISSUE THREAD

**Issue by dniasoff** [LINBIT/linstor-gui#3]
Hi Linbit

Thanks for making this open-source - really appreciated. Will help me to understand how the various components tie together.

Deployed using apt linstor-gui package.

Set up nginx 
```
  # Define the root directory for your static files
    root /usr/share/linstor-server/ui/;

    # Configure access to static files
    location / {
        try_files $uri $uri/ =404;
    }
```
However getting

![image](https://github.com/user-attachments/assets/84355c74-0b18-4d2c-96e0-8af97bac84f6)

Seeing these errors in my browser

![image](https://github.com/user-attachments/assets/b1891277-3e41-4aea-9a37-416549032d92)

I assume I am missing a config file with environment variables or something?

**Comment by Liang0028** [comment]
This package does not have a standalone server; it requires the LINSTOR environment and serves files through the LINSTOR server. It should be installed on the machine running the LINSTOR controller. After installation, it can be accessed via a URL like `http://192.168.123.105:3370/ui/#!/`, replacing `192.168.123.105` with the IP address of your LINSTOR controller.

**Comment by dniasoff** [comment]
Thanks for your response - I have updated controller and restarted systemd service (all installed via apt on Ubuntu jammy)

But getting

![image](https://github.com/user-attachments/assets/bf05f90c-c65a-49af-bd4c-34203cb7dc70)

**Comment by Liang0028** [comment]
I suggest updating to `v1.8.1` and trying again.

**Comment by dniasoff** [comment]
Thanks, it works after updating to v1.8.1 👍
